version: '3'

services:
  web:
    build: ./docker/web
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - ./docker/web/sites-available:/etc/apache2/sites-available

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telegrams
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
