version: '3'

services:
  web:
    build: ./docker/web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/web/sites-available:/etc/apache2/sites-available

  db:
    image: postgres
    restart: always
    ports:
      - "5555:5555"
    environment:
      POSTGRES_DB: telegram-bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
